### ISSUE TITLE
Refactor textarea to list of DOM elements

### ISSUE THREAD

**Issue by ventolingsv** [hiper2d/awesome-dice-room#2]
We should refactor chatbox textarea in room component, to use list of DOM elements instead
Number of elements should be limited, when new added over capaciti the oldest one should be removed

**Comment by hiper2d** [comment]
Let's fix the scrolling in the scope of this issue.

```
RoomComponent.html:
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'scrollTop: 313'. Current value: 'scrollTop: 317'
```
